31 role controller
IrynaPanchuk97/TransIT.API pull request #103
Opened 2019-04-12 16:51 UTC by danylo-dudok

2019-04-13 13:55 UTC, CrazyRoka requested changes

2019-04-13 13:55 UTC, RostyslavToch commented on TransIT.API/appsettings.Development.json
> +    "DefaultConnection": "Data Source=localhost;Initial Catalog=TransITDB;persist security info=True;user id=sa;password=i.am.using.docker;"
Remove this

2019-04-13 18:48 UTC, CrazyRoka approved these changes

2019-04-15 09:16 UTC, maksym-yaremko approved these changes

2019-04-15 09:17 UTC, merged