126 filtering
IrynaPanchuk97/TransIT.API pull request #127
Opened 2019-04-30 19:02 UTC by danylo-dudok

2019-05-01 13:35 UTC, CrazyRoka requested changes

2019-05-01 13:35 UTC, RostyslavToch commented on TransIT.API/Controllers/DataController.cs
> +            sequence.Select(entity => _mapper.Map<TEntityDTO>(entity));
`_mapper.Map<IEnumerable<TEntityDTO>>(sequence);`
I think this will be faster and more readable

2019-05-02 09:35 UTC, IrynaPanchuk97 approved these changes

2019-05-02 10:03 UTC, IrynaPanchuk97 approved these changes

2019-05-02 12:21 UTC, CrazyRoka approved these changes

2019-05-02 12:24 UTC, merged