add pass hasher if update pass
IrynaPanchuk97/TransIT.API pull request #134
Opened 2019-05-05 18:53 UTC by IrynaPanchuk97

2019-05-05 21:30 UTC, CrazyRoka requested changes

2019-05-05 21:30 UTC, RostyslavToch commented on TransIT.BLL/Services/ImplementedServices/UserService.cs
> +        public new virtual async Task<User> UpdateAsync(User model)
It must **override**

2019-05-05 21:30 UTC, RostyslavToch commented on TransIT.BLL/Services/ImplementedServices/UserService.cs
> +                model.Password = _hasher.HashPassword(model.Password);
That's bad! We must have separate endpoint for password updating
`POST api/v1/users/password`
And create separate method in UserService for that!

2019-05-06 10:28 UTC, CrazyRoka approved these changes

2019-05-06 10:35 UTC, danylo-dudok approved these changes

2019-05-06 10:36 UTC, merged