32 automapper
IrynaPanchuk97/TransIT.API pull request #33
Opened 2019-04-07 10:38 UTC by danylo-dudok

2019-04-07 11:44 UTC, CrazyRoka requested changes

2019-04-07 11:44 UTC, RostyslavToch commented on TransIT.DAL/Models/Mappings/ApplicationProfile.cs
> +                .ForMember(u => u.Role.Name, map => map.MapFrom(m => m.Role));
This mapping will throw an exception because not all fields are filled...
Try it

2019-04-07 13:18 UTC, IrynaPanchuk97 approved these changes

2019-04-08 07:37 UTC, markiyanshvets approved these changes

2019-04-08 07:40 UTC, CrazyRoka approved these changes

2019-04-08 07:40 UTC, merged