malfunction api
IrynaPanchuk97/TransIT.API pull request #88
Opened 2019-04-10 15:57 UTC by maksym-yaremko

#73

2019-04-10 17:34 UTC, CrazyRoka requested changes

2019-04-10 17:34 UTC, RostyslavToch commented on TransIT.API/Controllers/MalfunctionController.cs
> +        [Authorize(Roles = "ADMIN,WORKER,ENGINEER,CUSTOMER,ANALYST")]
Do we need authorize everywhere?
It can be applied to the class itself

2019-04-10 17:37 UTC, CrazyRoka approved these changes

2019-04-11 13:44 UTC, TarasKvasnytsya approved these changes

2019-04-11 13:48 UTC, merged